# Generated by Django 4.1.2 on 2022-10-25 10:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="description_uz"
                    ),
                ),
            ],
            options={
                "verbose_name": "Biz Haqimizda",
            },
        ),
        migrations.CreateModel(
            name="AboutImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="name_uz"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/about",
                        verbose_name="image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=65, null=True, verbose_name="name"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/category_image",
                        verbose_name="image",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myprint.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65, verbose_name="name")),
                ("number", models.IntegerField(verbose_name="number")),
                ("info", models.CharField(max_length=65, verbose_name="info")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="media/contact", verbose_name="image"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_name_order",
                    models.CharField(max_length=300, verbose_name="id_name_order"),
                ),
                ("client", models.CharField(max_length=65, verbose_name="client")),
                (
                    "client_phone_number",
                    models.CharField(max_length=65, verbose_name="client_phone_number"),
                ),
                (
                    "manager_name",
                    models.CharField(max_length=65, verbose_name="manager_name"),
                ),
                ("date_order", models.DateTimeField(verbose_name="date_order")),
                (
                    "ready_product_date_order",
                    models.DateTimeField(verbose_name="ready_product_date_order"),
                ),
            ],
            options={
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dizayn",
            },
        ),
        migrations.CreateModel(
            name="DigitalPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("size", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("on_site_print", models.CharField(max_length=50)),
                ("double_site_print", models.CharField(max_length=50)),
                ("size1", models.CharField(blank=True, max_length=100, null=True)),
                ("type1", models.CharField(blank=True, max_length=50, null=True)),
                ("on_site_print1", models.CharField(max_length=50)),
                ("double_site_print1", models.CharField(max_length=50)),
                ("size2", models.CharField(blank=True, max_length=100, null=True)),
                ("type2", models.CharField(blank=True, max_length=50, null=True)),
                ("on_site_print2", models.CharField(max_length=50)),
                ("double_site_print2", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
            ],
            options={
                "verbose_name": "Raqamli chop etish",
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=65, verbose_name="full_name"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="phone_number"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfoProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=65, verbose_name="size")),
                ("element", models.CharField(max_length=65, verbose_name="element")),
            ],
        ),
        migrations.CreateModel(
            name="InfoType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=65, verbose_name="size")),
                (
                    "type_paper",
                    models.CharField(max_length=65, verbose_name="type_paper"),
                ),
                (
                    "one_site_print",
                    models.CharField(max_length=65, verbose_name="one_site_print"),
                ),
                (
                    "double_site_print",
                    models.CharField(max_length=65, verbose_name="double_site_print"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LargeFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField()),
                ("description", models.TextField()),
                ("product_name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("product_name1", models.CharField(max_length=50)),
                ("type1", models.CharField(blank=True, max_length=50, null=True)),
                ("price1", models.CharField(blank=True, max_length=50, null=True)),
                ("type2", models.CharField(blank=True, max_length=50, null=True)),
                ("price2", models.CharField(blank=True, max_length=50, null=True)),
                ("product_name2", models.CharField(max_length=50)),
                ("type3", models.CharField(blank=True, max_length=50, null=True)),
                ("price3", models.CharField(blank=True, max_length=50, null=True)),
                ("product_name4", models.CharField(max_length=50)),
                ("type4", models.CharField(blank=True, max_length=50, null=True)),
                ("price4", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
            ],
            options={
                "verbose_name": "Katta formatda chop etish",
            },
        ),
        migrations.CreateModel(
            name="LaserPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("size", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("size1", models.CharField(blank=True, max_length=50, null=True)),
                ("price1", models.CharField(blank=True, max_length=50, null=True)),
                ("size2", models.CharField(blank=True, max_length=50, null=True)),
                ("price2", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=50,
                        null=True,
                        upload_to="media/serviceee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lazerni chop etish",
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65, verbose_name="name")),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/portfolio", verbose_name="image"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="key",
                    ),
                ),
                ("value", models.TextField(verbose_name="value")),
            ],
            options={
                "verbose_name": "Sozlama",
                "verbose_name_plural": "Sozlamalar",
            },
        ),
        migrations.CreateModel(
            name="Sponsors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65, verbose_name="name")),
                (
                    "image",
                    models.FileField(
                        upload_to="media/pictures/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "svg"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65, verbose_name="name")),
            ],
        ),
        migrations.CreateModel(
            name="TextPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("size", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("size1", models.CharField(blank=True, max_length=50, null=True)),
                ("price1", models.CharField(blank=True, max_length=50, null=True)),
                ("size2", models.CharField(blank=True, max_length=50, null=True)),
                ("price2", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=50,
                        null=True,
                        upload_to="media/serviceee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tekstilni chop etish",
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65, verbose_name="name")),
            ],
            options={
                "verbose_name": "Xizmat ko'rsatish turlari",
            },
        ),
        migrations.CreateModel(
            name="Type2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65)),
            ],
            options={
                "verbose_name": "Xizmat turlari",
            },
        ),
        migrations.CreateModel(
            name="TypeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65, verbose_name="name")),
                ("image", models.ImageField(upload_to="media/typeserveis")),
            ],
            options={
                "verbose_name": "Xizmat turi",
            },
        ),
        migrations.CreateModel(
            name="Type_Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shiroki_size",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="shiroki_size",
                    ),
                ),
                (
                    "shiroki_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="shiroki_name",
                    ),
                ),
                (
                    "shiroki_price",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="shiroki_price",
                    ),
                ),
                (
                    "tekstil_size",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="tekstil_size",
                    ),
                ),
                (
                    "tekstil_price",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="tekstil_price",
                    ),
                ),
                (
                    "lazer_size",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="lazer_size",
                    ),
                ),
                (
                    "lazer_price",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="lazer_price",
                    ),
                ),
                (
                    "type_paper",
                    models.CharField(
                        blank=True, max_length=65, null=True, verbose_name="qog'oz_turi"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="razmeri",
                    ),
                ),
                (
                    "one_site_print",
                    models.CharField(
                        blank=True,
                        max_length=65,
                        null=True,
                        verbose_name="bir tomonlama chop etish",
                    ),
                ),
                (
                    "double_site_print",
                    models.CharField(
                        blank=True,
                        max_length=65,
                        null=True,
                        verbose_name="ikki tomonlama chop etish",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="media/service"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="media/service"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="media/service"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="myprint.type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bizning xizmatlar",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65, verbose_name="name")),
                (
                    "image",
                    models.ImageField(upload_to="media/product", verbose_name="image"),
                ),
                ("vendor_code", models.CharField(max_length=20)),
                ("description", models.TextField(verbose_name="description")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myprint.category",
                    ),
                ),
                (
                    "info_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myprint.infoproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maxsulot",
                "verbose_name_plural": "Maxsulotlar",
            },
        ),
        migrations.CreateModel(
            name="OrderService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=65, verbose_name="full_name")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="phone_number"),
                ),
                ("creat_add", models.DateTimeField(auto_now_add=True)),
                (
                    "order_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myprint.type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat ko'rsatish zakazlari",
            },
        ),
        migrations.CreateModel(
            name="OrderForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=65, null=True, verbose_name="name"
                    ),
                ),
                (
                    "status_order",
                    models.CharField(
                        blank=True,
                        choices=[("шт", "шт"), ("усл", "усл")],
                        default="шт",
                        max_length=20,
                        null=True,
                        verbose_name="status_order",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(blank=True, null=True, verbose_name="amount"),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="price"
                    ),
                ),
                (
                    "price_free_VAT",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="price_free_VAT"
                    ),
                ),
                ("VAT", models.FloatField(blank=True, null=True, verbose_name="VAT")),
                (
                    "price_with_VAT",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="price_with_VAT"
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="total"
                    ),
                ),
                (
                    "total_price_with_VAT",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="total_price_with_VAT"
                    ),
                ),
                (
                    "total_price_ALL",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="total_price_ALL"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="myprint.customer",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="MenuTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65, verbose_name="name")),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/imagesTariff", verbose_name="image"
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myprint.tariff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65, verbose_name="name")),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/menuservice", verbose_name="image"
                    ),
                ),
                (
                    "type_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myprint.typeservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menyu Xizmati",
            },
        ),
        migrations.CreateModel(
            name="Image2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="media/service"),
                ),
                (
                    "type_sevice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myprint.type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat ko'rsatish rasmlari",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="media/service"),
                ),
                (
                    "type_sevice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myprint.type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rasm",
                "verbose_name_plural": "Rasmlar",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="first_name"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="full_name"
                    ),
                ),
                (
                    "phone_number",
                    models.IntegerField(
                        blank=True, unique=True, verbose_name="phone_number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=25, null=True, verbose_name="email address"
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superadmin", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager",
                "verbose_name_plural": "Managers",
            },
        ),
    ]
