# Generated by Django 4.1.2 on 2022-10-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="logo",
            field=models.ImageField(
                default=0, upload_to="media/logo", verbose_name="logo"
            ),
            preserve_default=False,
        ),
    ]
