# Generated by Django 4.1.2 on 2022-10-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="logo",
        ),
    ]
