# Generated by Django 4.1.2 on 2022-11-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(default=0, upload_to=""),
            preserve_default=False,
        ),
    ]
