# Generated by Django 4.1.2 on 2022-10-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=0, verbose_name="slug"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=0, verbose_name="slug"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=500, verbose_name="description"),
        ),
    ]
