# Generated by Django 4.1.2 on 2022-10-27 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0002_sublargeformat_alter_largeformat_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="digitalprint",
            name="double_site_print",
        ),
        migrations.RemoveField(
            model_name="digitalprint",
            name="double_site_print1",
        ),
        migrations.RemoveField(
            model_name="digitalprint",
            name="double_site_print2",
        ),
        migrations.RemoveField(
            model_name="digitalprint",
            name="on_site_print",
        ),
        migrations.RemoveField(
            model_name="digitalprint",
            name="on_site_print1",
        ),
        migrations.RemoveField(
            model_name="digitalprint",
            name="on_site_print2",
        ),
        migrations.RemoveField(
            model_name="digitalprint",
            name="size",
        ),
        migrations.RemoveField(
            model_name="digitalprint",
            name="size1",
        ),
        migrations.RemoveField(
            model_name="digitalprint",
            name="size2",
        ),
        migrations.RemoveField(
            model_name="digitalprint",
            name="type",
        ),
        migrations.RemoveField(
            model_name="digitalprint",
            name="type1",
        ),
        migrations.RemoveField(
            model_name="digitalprint",
            name="type2",
        ),
        migrations.CreateModel(
            name="SubDigitalPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("on_site_print", models.CharField(max_length=50)),
                ("double_site_print", models.CharField(max_length=50)),
                (
                    "all1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myprint.digitalprint",
                    ),
                ),
            ],
        ),
    ]
