# Generated by Django 4.1.2 on 2022-10-18 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0002_alter_orderform_vat_alter_orderform_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="name_ru",
        ),
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(default=0, max_length=65, verbose_name="name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myprint.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/category_image",
                verbose_name="image",
            ),
        ),
    ]
