# Generated by Django 4.1.2 on 2022-10-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0002_settings_logo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CEO",
        ),
        migrations.DeleteModel(
            name="Printer",
        ),
        migrations.DeleteModel(
            name="SocialMedia",
        ),
    ]
