# Generated by Django 4.1.2 on 2022-10-24 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0002_remove_settings_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsors",
            name="image",
            field=models.FileField(
                upload_to="media/pictures/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf", "doc", "svg"])
                ],
            ),
        ),
    ]
