# Generated by Django 4.1.2 on 2022-11-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0002_subcategory_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsors",
            name="name",
        ),
    ]
