# Generated by Django 4.1.2 on 2022-11-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0003_remove_sponsors_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="largeformat",
            options={"verbose_name": "Katta formatda chop etish"},
        ),
        migrations.AlterModelOptions(
            name="portfolio",
            options={"verbose_name": "Portfolio"},
        ),
        migrations.AlterModelOptions(
            name="sponsors",
            options={"verbose_name": "Sponsors"},
        ),
        migrations.RemoveField(
            model_name="orderform",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="orderform",
            name="name_uz",
        ),
    ]
