# Generated by Django 4.1.2 on 2022-10-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0003_delete_ceo_delete_printer_delete_socialmedia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
    ]
