# Generated by Django 4.1.2 on 2022-10-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "myprint",
            "0003_alter_category_options_rename_name_category_name_ru_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="info_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myprint.infoproduct",
            ),
        ),
    ]
