# Generated by Django 4.1.2 on 2022-10-27 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0003_remove_digitalprint_double_site_print_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textprint",
            name="price",
        ),
        migrations.RemoveField(
            model_name="textprint",
            name="price1",
        ),
        migrations.RemoveField(
            model_name="textprint",
            name="price2",
        ),
        migrations.RemoveField(
            model_name="textprint",
            name="size",
        ),
        migrations.RemoveField(
            model_name="textprint",
            name="size1",
        ),
        migrations.RemoveField(
            model_name="textprint",
            name="size2",
        ),
        migrations.CreateModel(
            name="SUbTextPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                (
                    "txt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myprint.textprint",
                    ),
                ),
            ],
        ),
    ]
