# Generated by Django 4.1.2 on 2022-11-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0003_remove_sponsors_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderform",
            name="status_order",
            field=models.CharField(
                blank=True,
                choices=[("ta", "ta"), ("kg", "kg")],
                default="шт",
                max_length=20,
                null=True,
                verbose_name="status_order",
            ),
        ),
    ]
