# Generated by Django 4.1.2 on 2022-10-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0004_remove_textprint_price_remove_textprint_price1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laserprint",
            name="price",
        ),
        migrations.RemoveField(
            model_name="laserprint",
            name="price1",
        ),
        migrations.RemoveField(
            model_name="laserprint",
            name="price2",
        ),
        migrations.RemoveField(
            model_name="laserprint",
            name="size",
        ),
        migrations.RemoveField(
            model_name="laserprint",
            name="size1",
        ),
        migrations.RemoveField(
            model_name="laserprint",
            name="size2",
        ),
        migrations.CreateModel(
            name="SubLaserPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myprint.laserprint",
                    ),
                ),
            ],
        ),
    ]
