# Generated by Django 4.1.2 on 2022-10-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0004_homedescription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomeDescription",
        ),
    ]
