# Generated by Django 4.1.2 on 2022-10-18 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0004_alter_product_info_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_uz", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Biz Haqimizda",
            },
        ),
        migrations.CreateModel(
            name="AboutImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="media/about"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "key",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
            ],
            options={
                "verbose_name": "Sozlama",
                "verbose_name_plural": "Sozlamalar",
            },
        ),
        migrations.AlterModelOptions(
            name="menuservice",
            options={"verbose_name": "Menyu Xizmati"},
        ),
        migrations.AlterModelOptions(
            name="typeservice",
            options={"verbose_name": "Xizmat turi"},
        ),
        migrations.RenameField(
            model_name="menuservice",
            old_name="name",
            new_name="name_uz",
        ),
        migrations.RenameField(
            model_name="typeservice",
            old_name="name",
            new_name="name_uz",
        ),
        migrations.AddField(
            model_name="typeservice",
            name="image",
            field=models.ImageField(default=0, upload_to="media/typeserveis"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menuservice",
            name="type_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myprint.typeservice",
            ),
        ),
    ]
