# Generated by Django 4.1.2 on 2022-10-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0004_delete_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                blank=True, max_length=65, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_uz",
            field=models.CharField(
                blank=True, max_length=65, null=True, verbose_name="name"
            ),
        ),
    ]
