# Generated by Django 4.1.2 on 2022-10-18 07:31

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        (
            "myprint",
            "0005_about_aboutimage_settings_alter_menuservice_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutimage",
            name="name_ru",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
