# Generated by Django 4.1.2 on 2022-10-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0005_remove_laserprint_price_remove_laserprint_price1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderservice",
            name="files",
            field=models.FileField(
                blank=True, null=True, upload_to="media/file", verbose_name="files"
            ),
        ),
    ]
