# Generated by Django 4.1.2 on 2022-10-24 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0005_alter_category_name_ru_alter_category_name_uz"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type_Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shiroki_size",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="shiroki_size",
                    ),
                ),
                (
                    "shiroki_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="shiroki_name",
                    ),
                ),
                (
                    "shiroki_price",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="shiroki_price",
                    ),
                ),
                (
                    "tekstil_size",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="tekstil_size",
                    ),
                ),
                (
                    "tekstil_price",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="tekstil_price",
                    ),
                ),
                (
                    "lazer_size",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="lazer_size",
                    ),
                ),
                (
                    "lazer_price",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="lazer_price",
                    ),
                ),
                (
                    "type_paper",
                    models.CharField(
                        blank=True, max_length=65, null=True, verbose_name="qog'oz_turi"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=65,
                        null=True,
                        verbose_name="razmeri",
                    ),
                ),
                (
                    "one_site_print",
                    models.CharField(
                        blank=True,
                        max_length=65,
                        null=True,
                        verbose_name="bir tomonlama chop etish",
                    ),
                ),
                (
                    "double_site_print",
                    models.CharField(
                        blank=True,
                        max_length=65,
                        null=True,
                        verbose_name="ikki tomonlama chop etish",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="media/service"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="media/service"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="media/service"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="myprint.type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bizning xizmatlar",
            },
        ),
    ]
