# Generated by Django 4.1.2 on 2022-10-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0005_delete_homedescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dizayn",
            },
        ),
        migrations.CreateModel(
            name="DigitalPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("description", models.TextField()),
                ("size", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("on_site_print", models.CharField(max_length=50)),
                ("double_site_print", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
            ],
            options={
                "verbose_name": "Raqamli chop etish",
            },
        ),
        migrations.CreateModel(
            name="LargeFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField()),
                ("description", models.TextField()),
                ("product_name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
            ],
            options={
                "verbose_name": "Katta formatda chop etish",
            },
        ),
        migrations.CreateModel(
            name="LaserPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("size", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=50,
                        null=True,
                        upload_to="media/serviceee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lazerni chop etish",
            },
        ),
        migrations.CreateModel(
            name="TextPrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("size", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=50,
                        null=True,
                        upload_to="media/serviceee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tekstilni chop etish",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Xizmat ko'rsatish rasmlari"},
        ),
        migrations.RemoveField(
            model_name="image",
            name="type_sevice",
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/serviceee"),
        ),
        migrations.AddField(
            model_name="image",
            name="designe",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designe",
                to="myprint.design",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="digitalPrint",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="digitalPrint",
                to="myprint.design",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="largeFormat",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="largeFormat",
                to="myprint.design",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="laserPrint",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="laserPrint",
                to="myprint.design",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="image",
            name="textPrint",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="textPrint",
                to="myprint.design",
            ),
            preserve_default=False,
        ),
    ]
