# Generated by Django 4.1.2 on 2022-10-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "myprint",
            "0006_design_digitalprint_largeformat_laserprint_textprint_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Rasm", "verbose_name_plural": "Rasmlar"},
        ),
        migrations.RemoveField(
            model_name="image",
            name="designe",
        ),
        migrations.RemoveField(
            model_name="image",
            name="digitalPrint",
        ),
        migrations.RemoveField(
            model_name="image",
            name="largeFormat",
        ),
        migrations.RemoveField(
            model_name="image",
            name="laserPrint",
        ),
        migrations.RemoveField(
            model_name="image",
            name="textPrint",
        ),
        migrations.AddField(
            model_name="image",
            name="type_sevice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myprint.type",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/service"),
        ),
        migrations.CreateModel(
            name="Image2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/serviceee"
                    ),
                ),
                (
                    "designe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designe",
                        to="myprint.design",
                    ),
                ),
                (
                    "digitalPrint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digitalPrint",
                        to="myprint.design",
                    ),
                ),
                (
                    "largeFormat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="largeFormat",
                        to="myprint.design",
                    ),
                ),
                (
                    "laserPrint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laserPrint",
                        to="myprint.design",
                    ),
                ),
                (
                    "textPrint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="textPrint",
                        to="myprint.design",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat ko'rsatish rasmlari",
            },
        ),
    ]
