# Generated by Django 4.1.2 on 2022-10-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0006_orderservice_files"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuTariff",
        ),
        migrations.DeleteModel(
            name="Tariff",
        ),
    ]
