# Generated by Django 4.1.2 on 2022-10-24 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0006_type_services"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="type",
            options={"verbose_name": "Xizmat ko'rsatish turlari"},
        ),
        migrations.RenameField(
            model_name="type",
            old_name="name",
            new_name="name_uz",
        ),
        migrations.RemoveField(
            model_name="type",
            name="infotype",
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="media/service"),
                ),
                (
                    "type_sevice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myprint.type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rasm",
                "verbose_name_plural": "Rasmlar",
            },
        ),
    ]
