# Generated by Django 4.1.2 on 2022-10-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0006_aboutimage_name_ru"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutimage",
            name="name_ru",
        ),
        migrations.AlterField(
            model_name="about",
            name="description_uz",
            field=models.TextField(
                blank=True, null=True, verbose_name="description_uz"
            ),
        ),
        migrations.AlterField(
            model_name="aboutimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/about", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="aboutimage",
            name="name_uz",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="name_uz"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="client",
            field=models.CharField(max_length=65, verbose_name="client"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="client_phone_number",
            field=models.CharField(max_length=65, verbose_name="client_phone_number"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="date_order",
            field=models.DateTimeField(verbose_name="date_order"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id_name_order",
            field=models.CharField(max_length=300, verbose_name="id_name_order"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="manager_name",
            field=models.CharField(max_length=65, verbose_name="manager_name"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="ready_product_date_order",
            field=models.DateTimeField(verbose_name="ready_product_date_order"),
        ),
        migrations.AlterField(
            model_name="form",
            name="full_name",
            field=models.CharField(max_length=65, verbose_name="full_name"),
        ),
        migrations.AlterField(
            model_name="form",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="phone_number"),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="VAT",
            field=models.FloatField(blank=True, null=True, verbose_name="VAT"),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="amount",
            field=models.IntegerField(blank=True, null=True, verbose_name="amount"),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="name",
            field=models.CharField(
                blank=True, max_length=65, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="price_free_VAT",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="price_free_VAT"
            ),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="price_with_VAT",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="price_with_VAT"
            ),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="status_order",
            field=models.CharField(
                blank=True,
                choices=[("шт", "шт"), ("усл", "усл")],
                default="шт",
                max_length=20,
                null=True,
                verbose_name="status_order",
            ),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="total",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="total"
            ),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="total_price_ALL",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="total_price_ALL"
            ),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="total_price_with_VAT",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="total_price_with_VAT"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="key",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="key"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="value",
            field=models.TextField(verbose_name="value"),
        ),
    ]
