# Generated by Django 4.1.2 on 2022-10-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0007_alter_image_options_remove_image_designe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Type2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=65)),
            ],
            options={
                "verbose_name": "Xizmat ko'rsatish turlari",
            },
        ),
        migrations.RemoveField(
            model_name="image2",
            name="designe",
        ),
        migrations.RemoveField(
            model_name="image2",
            name="digitalPrint",
        ),
        migrations.RemoveField(
            model_name="image2",
            name="largeFormat",
        ),
        migrations.RemoveField(
            model_name="image2",
            name="laserPrint",
        ),
        migrations.RemoveField(
            model_name="image2",
            name="textPrint",
        ),
        migrations.AddField(
            model_name="image2",
            name="type_sevice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myprint.type",
            ),
        ),
        migrations.AlterField(
            model_name="image2",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/service"),
        ),
    ]
