# Generated by Django 4.1.2 on 2022-10-24 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0007_alter_type_options_rename_name_type_name_uz_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=65, verbose_name="full_name")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="phone_number"),
                ),
                ("creat_add", models.DateTimeField(auto_now_add=True)),
                (
                    "order_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myprint.type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat ko'rsatish zakazlari",
            },
        ),
    ]
