# Generated by Django 4.1.2 on 2022-10-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0007_delete_menutariff_delete_tariff"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="Form",
        ),
        migrations.DeleteModel(
            name="InfoType",
        ),
    ]
