# Generated by Django 4.1.2 on 2022-10-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0008_type2_remove_image2_designe_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="type2",
            options={"verbose_name": "Xizmat turlari"},
        ),
    ]
